services:
  - type: web
    name: disposms-enhanced
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: HOST
        value: 0.0.0.0
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
    autoDeploy: true
    branch: main
    rootDir: .
    
  - type: redis
    name: disposms-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    
databases:
  - name: disposms-mongodb
    databaseName: disposms
    user: disposms
    plan: starter

